# [[150, 600], [-300, 300], [100, 100]]
robot_count: 4

points_range:
  -
    - 150
    - 600
  -
    - -300
    - 300
  -
    - 0
    - 0

linkWidth: 200

originalPosture:
  - 90
  - 45
  - -45
  - 0
  - 90
  - 0

axisRange:
  -
    - -170
    - 170
  -
    - -110
    - 120
  -
    - -204
    - 69
  -
    - -190
    - 190
  -
    - -120
    - 120
  -
    - -360
    - 360

direct_array:
  -
    - 0
    - 0
    - -1
  -
    - 0
    - 1
    - 0
  -
    - 1
    - 0
    - 0