robots_count: 4

points_range:
  -
    - 150
    - 850
  -
    - -350
    - 350
  -
    - 0
    - 0

link_width: 200

org_pos:
  - 90
  - 45
  - -45
  - 0
  - 90
  - 0

joints_range:
  -
    - -170
    - 170
  -
    - -110
    - 120
  -
    - -204
    - 69
  -
    - -190
    - 190
  -
    - -120
    - 120
  -
    - -360
    - 360

direct_array:
  -
    - 0
    - 0
    - -1
  -
    - 0
    - 1
    - 0
  -
    - 1
    - 0
    - 0